tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary-fixed-dim": "#e7bdb1",
                "surface-container-low": "#f5f5dc",
                "on-error-container": "#93000a",
                "tertiary-container": "#2e5000",
                "tertiary": "#1e3700",
                "on-tertiary-fixed-variant": "#2e4f00",
                "on-secondary-fixed-variant": "#004a75",
                "surface-dim": "#dbdcc3",
                "on-surface-variant": "#504441",
                "on-surface": "#1b1d0e",
                "on-primary-fixed-variant": "#5d4037",
                "inverse-on-surface": "#f2f2d9",
                "tertiary-fixed-dim": "#9ed75b",
                "secondary-fixed-dim": "#96ccff",
                "surface-container": "#efefd7",
                "primary-fixed": "#ffdbd0",
                "surface-tint": "#77574d",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e4e4cc",
                "on-secondary": "#ffffff",
                "error": "#ba1a1a",
                "primary": "#442a22",
                "on-primary-container": "#d4ada1",
                "on-tertiary-fixed": "#0f2000",
                "on-background": "#1b1d0e",
                "error-container": "#ffdad6",
                "background": "#fbfbe2",
                "surface-bright": "#fbfbe2",
                "outline-variant": "#d4c3be",
                "surface-variant": "#e4e4cc",
                "on-error": "#ffffff",
                "outline": "#827470",
                "on-secondary-fixed": "#001d32",
                "surface-container-high": "#eaead1",
                "tertiary-fixed": "#b9f474",
                "on-tertiary": "#ffffff",
                "on-primary-fixed": "#2c160e",
                "primary-container": "#5d4037",
                "inverse-primary": "#e7bdb1",
                "on-primary": "#ffffff",
                "on-secondary-container": "#00436a",
                "inverse-surface": "#303221",
                "secondary-fixed": "#cee5ff",
                "surface": "#fbfbe2",
                "secondary-container": "#51b2fe",
                "secondary": "#00639a",
                "on-tertiary-container": "#8ec64c"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "16px",
                "stack-md": "24px",
                "gutter": "24px",
                "container-max": "1280px",
                "margin-desktop": "48px",
                "stack-lg": "48px",
                "base": "8px",
                "stack-sm": "12px"
            },
            "fontFamily": {
                "body-md": ["Inter"],
                "label-md": ["JetBrains Mono"],
                "headline-sm": ["Montserrat"],
                "display-lg-mobile": ["Montserrat"],
                "label-sm": ["JetBrains Mono"],
                "display-lg": ["Montserrat"],
                "headline-md": ["Montserrat"],
                "body-lg": ["Inter"]
            },
            "fontSize": {
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
            }
        },
    },
}
